name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy artifacts
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Bundle
      uses: swiftwasm/swiftwasm-action@v5.8
      with:
        shell-action: carton bundle
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./Bundle
